### ISSUE TITLE
Severe Bobbing On Final

### ISSUE THREAD

**Issue by ThatOneAviator1987** [Ariakim-Taiyo/A321Neo-Expansion#1]
I tried to use this addon with the A321 Neo, It worked, but has a severe bobbing issue when in a downwind or short final.

**Comment by Ariakim-Taiyo** [comment]
It is best to not run this plugin on a low end device. If you are not using a low end device, then tell me as there is a problem if that is the case

**Comment by ThatOneAviator1987** [comment]
I'm running it on mid-end specs

-GeForce RTX 2070
-Gigabyte Z690 Aorus Pro
-Windows 10 
-Several Fans Attached to The Case

I also tried it on my chromebook, same results.

**Comment by Ariakim-Taiyo** [comment]
Hmm, i have noted an issue where the system will tend to overcompensate, but until then, it is best to make smooth and gradual control inputs, not sharp and jerky ones. I know that can be a challenge when on short final, so i will look into increasing the control damping for the FBW input.

**Comment by ThatOneAviator1987** [comment]
Thanks. Have a nice day Ariakim.
