### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by GoogleWasAllMyIdea** [Ariakim-Taiyo/A321Neo-Expansion#2]
Engine sounds do not work. Also the engines have no thrust either for takeoff and the startup menu doesnt work because neither engine starts to spin. Also GPWS dont work. Neither does the ILS. I think the entire menu is broken.

**Comment by GoogleWasAllMyIdea** [comment]
@Ariakim-Taiyo

**Comment by GoogleWasAllMyIdea** [comment]
When I press enter after pasting the code into console it prevents the engines from spinning even if I use "E" to start them or your Gui. The plane simply wont move I even tried setting a new thrust value to a high number and nothing happened. The instruments show the engine "Throttling up" But it doesn't make any sound or do anything to move the plane. It still flies but with no thrust so you have to glide but GPWS callouts work, but not the alarm system for some reason. 
Flaps sound works but PTU does not. Also the fly by wire system goes nuts and will always pitch me nose down and I can't recover unless I press enter while I am level. 
The ILS does not work either and won't even pop up. 
Am I doing something wrong?
Do I need proof?
Just tell me what I can do please because this sounds like a REALLY cool addon.

**Comment by Ariakim-Taiyo** [comment]
Ensure you are not pressing e when starting up. The e key is hardcoded into the sim as an engine startup/shutdown, but in the case of this addon its actually a shutdown. just dont mess with the e key. Here's a breakdown of what is happening:

You likely pressed e in the startup sequence the first time, shutting down the default RPM calculations, which the plugin relies on.

The best way to start the engines is on the ground, so that you don't have to wait for 2 minutes for the engines to start while losing altitude. once the engines are started they will stay on until you shut them down, even if you reset the flight.

The alarms are disabled when the plane is in approach config, meaning that the flaps are down and gear are down. The pull up alarm is an exception since it is rather important.

The engines take a lot longer to start up than the default 15 seconds, so be patient. the PTU will only sound when the engines are started independently.

**Comment by Ariakim-Taiyo** [comment]
You are also probably using the first version, and the pitch down tendency was overcompensation for the alpha protection. Basically, you almost stalled so it automatically pushed the nose down. I have since rewritten that feature so it only triggers post-stall and is much less pronounced. More of a nudge than a slam down. Much of the FBW control fighting was patched in the latest release as well.

**Comment by GoogleWasAllMyIdea** [comment]
OHHHH okay!!!

**Comment by GoogleWasAllMyIdea** [comment]
But when I press it nothing happens

**Comment by GoogleWasAllMyIdea** [comment]
Do i need to have the engines off before I hit enter with code? Or do i leave them running because when I press the start engine button for either one nothing happens after 5 minutes.

**Comment by Ariakim-Taiyo** [comment]
Hmm, the engines should be on by default, you just have to press the startup button.
Im not entirely sure how you are running it, are you using the google chrome console or a separate one? I know there are some issues running the plugin through third-party consoles. I do not know if there is anything i can do to fix this as it is simply a limitation of console plugins. Sadly my school started cracking down on coders and people like me circumventing their internet filters and now they blocked the default console. Of course they overlooked the bookmarklet plugins. I will probably now have some motivation to convert these plugins to bookmarklets now, but it will take a while to transcribe over 1k lines of code to strict mode.

**Comment by GoogleWasAllMyIdea** [comment]
Yeh I think that might be the problem then.

**Comment by Ariakim-Taiyo** [comment]
Just stay tuned for any bookmark conversions i make. I will be taking an indefinite break from development shortly, but im going to try and fix any major issues with my plugins first.

**Comment by GoogleWasAllMyIdea** [comment]
Here is what I did. 
I Copied the code. 
I Loaded into Geofs (NOT BETA)
I selected the A321-Neo
I teleported onto Miami Intl runway
I then used my bookmark to open "Console" 
I pasted the code in (not ctrl v because that activates replay) I just used "Paste" 
Then I closed the console after it was success "it said"
Then I clicked the "A321Neo" button that appeared
It opened and I selected to start left engine
The tab said it was playing audio but I have my volume on max and the site is not muted and Geofs is unmuted also
I waited TEN minutes and nothing happened
I tried the right engine
Then it stopped saying the tab was playing audio
Waited another ten minutes and still no sound and I tried setting throttle to max but the "gage" moved, while the plane did not.
I had the brakes off
I tried the "ILS" button and nothing happened either
After that I gave up and commented here. 
I repeated this 5 times with no luck.

**Comment by Ariakim-Taiyo** [comment]
I do believe that this is an issue with the bookmarklet console being unable to run HTML onclick functions, so i will contact the author of said bookmark. There is no current workaround.

**Comment by GoogleWasAllMyIdea** [comment]
javascript:(function()%7B(function() %7Bvar x %3D
document.createElement("script")%3Bx.src %3D
"https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2FSnowLord7%2Fdevconsole%40master%2Fmain.js"%3Bx.onload
%3D alert("Loaded Developer
Console!")%3Bdocument.head.appendChild(x)%3B%7D)()%7D)()
<about:blank#blocked>
That is the bookmark I use it is made by someone named "Snowlord"
Also your Earlier version of ILS worked with this but now it does not work
because of the buttons.
I think the buttons just can't execute something the button is supposed to.
Also the 777 revamp works with this too.
And the Livery changer does too.
Even the AP++ works with this.

**Comment by Ariakim-Taiyo** [comment]
I have looked into it and the plugins that work do not rely on HTML onclick to work. All of the console based plugins should work. 

I have a workaround to the issue of the UI not working, but it relies on console functions;
To start the engines, execute the following:
`startEngine("left");`
`startEngine("right");`

To stop the engines run `stopEngines();`

To toggle the ILS;
`togglePanel();`

To toggle the terrain radar;
`radar();`

**Comment by GoogleWasAllMyIdea** [comment]
Thank you!!

**Comment by GoogleWasAllMyIdea** [comment]
. 
It didn't work.

**Comment by GoogleWasAllMyIdea** [comment]
I pasted the code after loading in to a runway and all that. 
Then I went back to console and put in the things to start the engines ONE AT A TIME. and it didn't work. 
I think there is more than one problem.

**Comment by GoogleWasAllMyIdea** [comment]
@Ariakim-Taiyo Just.. Nevermind. 
I don't want you to have to change something big in the code because of one person having issues. It works for most people so I will just deal with it thanks for trying anyways.

**Comment by Ariakim-Taiyo** [comment]
Well, I will have to figure out some workarounds since a majority of the community is stuck using the third party console, sadly that includes me now. (At least until i find a hacky way to bypass the console restriction again)

**Comment by GoogleWasAllMyIdea** [comment]
Okay. well if you do find a way to bypass and get the real console PLEASE
share this with me I have looked on every website I can find to see how I
can do it that would be amazing if you could find a way to get console.

**Comment by GoogleWasAllMyIdea** [comment]
@Ariakim-Taiyo I DID IT!!!! 
So I found a new bookmark that opens a third party console but it actually WORKS when i pasted the code into "console" it worked I started the engine and the ILS thing worked so now it is usable. 

This one can execute button functions unlike the other one. Here is the code for the bookmark:

javascript:(function () { var script = document.createElement('script'); script.src="//cdn.jsdelivr.net/npm/eruda"; document.body.appendChild(script); script.onload = function () { eruda.init() } })();

This worked 100% and ur addon is amazing!! Thank you!!

**Comment by GoogleWasAllMyIdea** [comment]
Also, I noticed something. On takeoff if I went into first person view the nose would IMMEDIATELY lift and cause a severe tailstrike and then when i went back into follow cam, the plane slammed the nose down  and began repeating "retard retard" over and over and i lost control. Maybe a bug?
I do love everything else about it. 
Is it possible for the plane to fly on one engine btw? or do they both still have the same amount of thrust no matter what.

**Comment by Ariakim-Taiyo** [comment]
Yes, it is possible to fly on one engine, but you will need a lot of rudder to keep it stable.

As for the other issue, I'm not too sure what would cause that, but i can look into it.

**Comment by GoogleWasAllMyIdea** [comment]
I figured out when you're on the ground if you go into first person the plane pitches up and the nose goes into the air, I think something with the hitboxes is causing this. 

Also I wanted to know why when you go to full power the engine noise sounds like it would if you were inside the plane but at 80% power it sounds really loud and like it is on the outside of the plane. Is this intentional, or....? 

Also maybe some suggestions. Maybe, like, you need the APU when the engines aren't running or else the strobe lights/cockpit PFD won't light up or turn on even when you press "L". Maybe you need to start the APU, and then the engines? I know this would be complicated for the engines to be started after the APU is started, but it would be a cool feature. 
Maybe even some tire screech noises when landing? 

LAST SUGGESTION (I don't think this is possible): Maybe you could add so we could have engine fire? It is already possible to have only one engine to fly on, which I only DREAMED would happen, and it did. So maybe you could press a button to fail the left or right engine and you can reposition the contrails so that they are directly behind the engine to create smoke, and then we can press the "Extinguish" button to put the engine out, making it inoperable until the flight is reset? I know that is probably impossible, but if it was that would be cool. 
Thanks for all you do!

(Also for some reason when I press "R" the game crashes when using this plugin on the A321 but idk why it ALWAYS crashes no matter what I do.)

**Comment by GoogleWasAllMyIdea** [comment]
@Ariakim-Taiyo So, I had a question (by the way this is off topic because it isn't about the A321 extension, because that is fine) 
I wanted to know what you were doing with the "UnreleasedGeofsGrabber" or something like that. I heard about it and wanted to know a few things.
1st: How do I use this?
2nd: What can it show me?
3rd: Would I be able to use that code to implement those aircraft into my Geofs (I have dev/ aircraft backend access thanks to Xavier)
and 4th: Is it in development still or is it useable right now? I am not experienced with replit and so I dunno where to use it. Do I just click "Run"? It shows a bunch of links in the "output" text thingy but when I go to the link (copy paste) it says error 404 nginx. 
AM I doing something wrong or is it just not ready yet? Thanks -Someone.

**Comment by Ariakim-Taiyo** [comment]
The program in question is a brute force url scraper similar to some tools such as dirbuster.

Currently it will generate a large array of all possible urls for the geofs backend repository and save them to an output file, which is the file you were looking at.

1. The program was not designed to be user friendly or intuitive, as I am the only person who would really need to run it.
2. It currently is unfinished and does not scan the urls themselves. as far as I am aware, most of the urls in the output file are invalid and are not yet tested. That will be stage 2 of the program which i have yet to write. It takes at least a full day to generate every url possible, and the final output file could exceed several gigabytes in size, so this will take some time to run.
3. The purpose of the program is to provide an index of all working aircraft URLs, whatever you choose to do with those URLs is up to you. I would not suggest trying to steal the code for your own projects, but simply uploading them to your backend to fly them around is fine.
4. As stated above, the program is unfinished. Once it is done it will check if the urls are valid before pushing the output file. I will upload the final list of aircraft urls to either here or my discord server when they are found.

**Comment by GoogleWasAllMyIdea** [comment]
I had no intent on stealing the code, I just wanted to fly them like you said. For fun, I guess. 
Let me know when you get the urls! I would love to try them. 
Also, your work is amazing, I wish I was as talented as you are at coding/scripting. 
Thank you again! -Person
(Also I am going through the links one by one and haven't found any that work yet but if I do I will let you know if you want.)

**Comment by GoogleWasAllMyIdea** [comment]
Alright, well, if you figure out any links let me know so I can try them! I love flying new planes, because it is an experience like no other.

**Comment by bonguxi** [comment]
so great thank you very much

**Comment by Ariakim-Taiyo** [comment]
this issue's been open for a whole year for really no reason lol
